"""Vercel Blob storage client (Plan 00034).

Uploads bytes to Vercel Blob via the HTTP API and returns a public URL.
Used for portrait images generated by ``openai_client.generate_image``.

Vercel Blob is the right home for these because:
- Free tier (Hobby) includes 1 GB storage + shared bandwidth — plenty
  for hundreds of portraits at 1–2 MB each.
- Permanent public URLs survive Render redeploys (Render's free tier
  filesystem is ephemeral).
- No SDK required — the upload is a single PUT with a bearer token.

Configure via the ``BLOB_READ_WRITE_TOKEN`` env var (created in the
Vercel dashboard: Storage → Blob → create store → API tokens).

If the token is missing, ``upload`` raises ``PermissionError`` — services
catch that and surface a user-friendly message.
"""

from __future__ import annotations

import os
import uuid as _uuid

import httpx

_BLOB_API = "https://blob.vercel-storage.com"


def _get_token() -> str:
    """Return the configured Blob read-write token or raise."""
    token = os.environ.get("BLOB_READ_WRITE_TOKEN", "").strip()
    if not token:
        raise PermissionError(
            "BLOB_READ_WRITE_TOKEN is not configured. "
            "Create a Vercel Blob store and copy its read-write token "
            "into the Render dashboard."
        )
    return token


def upload(
    *,
    path: str,
    data: bytes,
    content_type: str = "image/png",
) -> str:
    """Upload bytes to Vercel Blob and return the resulting public URL.

    Args:
        path: Logical path inside the blob store, e.g.
            ``"portraits/{uuid}.png"``. Vercel appends a random suffix
            to the filename for content-addressability unless
            ``add_random_suffix=false`` is sent.
        data: Raw bytes to upload (PNG, JPEG, etc.).
        content_type: MIME type to record on the object.

    Returns:
        Absolute public URL of the uploaded object.

    Raises:
        PermissionError: If ``BLOB_READ_WRITE_TOKEN`` is not set.
        RuntimeError: If the upload fails or the response is malformed.
    """
    token = _get_token()
    url = f"{_BLOB_API}/{path.lstrip('/')}"
    headers = {
        "authorization": f"Bearer {token}",
        "content-type": content_type,
        # Defeat Vercel's default random suffix so deterministic paths
        # (npc-{uuid}.png) don't get a second hash appended.
        "x-add-random-suffix": "0",
        "x-content-type": content_type,
    }
    try:
        resp = httpx.put(url, content=data, headers=headers, timeout=60.0)
    except httpx.HTTPError as exc:
        raise RuntimeError(f"Vercel Blob upload network error: {exc}") from exc
    if resp.status_code >= 400:
        raise RuntimeError(f"Vercel Blob upload failed ({resp.status_code}): {resp.text[:300]}")
    try:
        payload = resp.json()
    except ValueError as exc:
        raise RuntimeError(f"Vercel Blob response was not JSON: {resp.text[:300]}") from exc
    blob_url = payload.get("url")
    if not blob_url:
        raise RuntimeError(f"Vercel Blob response missing 'url': {payload!r}")
    return str(blob_url)


def portrait_path(entity_kind: str, entity_id: _uuid.UUID | str) -> str:
    """Build a deterministic blob path for a portrait.

    Args:
        entity_kind: ``"npc"`` or ``"pc"``.
        entity_id: UUID (or stringified UUID) of the entity.

    Returns:
        Blob path like ``portraits/npc-<uuid>.png``.
    """
    return f"portraits/{entity_kind}-{entity_id}.png"
