"""Vercel Blob storage client (Plan 00034).

Uploads bytes to Vercel Blob via the HTTP API and returns a public URL.
Used for portrait images generated by ``openai_client.generate_image``.

Vercel Blob is the right home for these because:
- Free tier (Hobby) includes 1 GB storage + shared bandwidth — plenty
  for hundreds of portraits at 1–2 MB each.
- Permanent public URLs survive Render redeploys (Render's free tier
  filesystem is ephemeral).
- No SDK required — the upload is a single PUT with a bearer token.

Configure via the ``BLOB_READ_WRITE_TOKEN`` env var (created in the
Vercel dashboard: Storage → Blob → create store → API tokens).

If the token is missing, ``upload`` raises ``PermissionError`` — services
catch that and surface a user-friendly message.
"""

from __future__ import annotations

import os
import uuid as _uuid

import httpx

_BLOB_API = "https://blob.vercel-storage.com"


def _get_token() -> str:
    """Return the configured Blob read-write token or raise."""
    token = os.environ.get("BLOB_READ_WRITE_TOKEN", "").strip()
    if not token:
        raise PermissionError(
            "BLOB_READ_WRITE_TOKEN is not configured. "
            "Create a Vercel Blob store and copy its read-write token "
            "into the Render dashboard."
        )
    return token


def upload(
    *,
    path: str,
    data: bytes,
    content_type: str = "image/png",
) -> str:
    """Upload bytes to Vercel Blob and return the resulting public URL.

    Vercel appends a random suffix to the filename — so every upload
    produces a UNIQUE URL. This is deliberate: Vercel Blob serves blobs
    through a CDN with a one-year ``immutable`` cache-control. If we
    reused a deterministic path (pc-<uuid>.png) the CDN would keep
    serving the FIRST image forever even after the bytes were
    overwritten — which is exactly the "regenerate portrait does
    nothing" bug. Unique URLs sidestep the CDN cache entirely: each
    regenerated portrait gets a fresh address, the entity's
    ``portrait_url`` is updated to point at it, and the immutable cache
    is now correct because each URL genuinely never changes.

    Trade-off: superseded blobs are orphaned in the store. At ~1.5 MB
    each on a 1 GB free tier that's hundreds of regens before it
    matters; add a sweep later if needed.

    Args:
        path: Logical path prefix inside the blob store, e.g.
            ``"portraits/pc-<uuid>.png"``. Vercel inserts a random hash
            before the extension to make the final URL unique.
        data: Raw bytes to upload (PNG, JPEG, etc.).
        content_type: MIME type to record on the object.

    Returns:
        Absolute public URL of the uploaded object (with random suffix).

    Raises:
        PermissionError: If ``BLOB_READ_WRITE_TOKEN`` is not set.
        RuntimeError: If the upload fails or the response is malformed.
    """
    token = _get_token()
    url = f"{_BLOB_API}/{path.lstrip('/')}"
    headers = {
        "authorization": f"Bearer {token}",
        "content-type": content_type,
        # x-add-random-suffix defaults to "1" — left at the default so
        # every upload gets a unique URL. See the docstring for why this
        # matters (Vercel CDN immutable-cache vs. deterministic paths).
        "x-content-type": content_type,
    }
    try:
        resp = httpx.put(url, content=data, headers=headers, timeout=60.0)
    except httpx.HTTPError as exc:
        raise RuntimeError(f"Vercel Blob upload network error: {exc}") from exc
    if resp.status_code >= 400:
        raise RuntimeError(f"Vercel Blob upload failed ({resp.status_code}): {resp.text[:300]}")
    try:
        payload = resp.json()
    except ValueError as exc:
        raise RuntimeError(f"Vercel Blob response was not JSON: {resp.text[:300]}") from exc
    blob_url = payload.get("url")
    if not blob_url:
        raise RuntimeError(f"Vercel Blob response missing 'url': {payload!r}")
    return str(blob_url)


def portrait_path(entity_kind: str, entity_id: _uuid.UUID | str) -> str:
    """Build the blob path prefix for a portrait.

    The entity kind + id keep the blob recognizable in the store, but
    Vercel inserts a random hash before the ``.png`` so the final URL is
    unique per upload (see ``upload`` docstring).

    Args:
        entity_kind: ``"npc"``, ``"pc"``, or ``"monster"``.
        entity_id: UUID (or stringified UUID) of the entity.

    Returns:
        Blob path prefix like ``portraits/npc-<uuid>.png`` — Vercel
        appends a random suffix on upload.
    """
    return f"portraits/{entity_kind}-{entity_id}.png"
