/**
 * D20Mark — QuestLab's die: a true icosahedron, face 20 toward you, lit from
 * the top-left, gold edges and numerals on crimson resin. Generated by
 * scratchpad/gen_d20.py (orthographic projection); do not hand-edit points.
 */
export default function D20Mark({ size = 140, glow = true, className }: { size?: number; glow?: boolean; className?: string }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="-1.12 -1.12 2.24 2.24"
      className={className}
      aria-hidden
      style={glow ? { filter: "drop-shadow(0 10px 22px rgba(0,0,0,0.6)) drop-shadow(0 0 18px rgba(201,168,76,0.28))" } : undefined}
    >
      <defs>
        <radialGradient id="d20-sheen" cx="35%" cy="28%" r="70%">
          <stop offset="0%" stop-color="#ffffff" stop-opacity="0.22" />
          <stop offset="55%" stop-color="#ffffff" stop-opacity="0.04" />
          <stop offset="100%" stop-color="#000000" stop-opacity="0.25" />
        </radialGradient>
      </defs>
      <g dangerouslySetInnerHTML={{ __html: BODY }} />
      <g dangerouslySetInnerHTML={{ __html: SHEEN }} />
    </svg>
  );
}

const BODY = `<polygon points="0.2306,-0.7771 0.1770,-0.8699 0.9507,-0.3094" fill="#621413" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.57"/>
<polygon points="0.2306,-0.7771 -0.6988,-0.7085 0.1770,-0.8699" fill="#ab2720" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.59"/>
<polygon points="0.5531,0.1984 0.9507,-0.3094 0.6988,0.7085" fill="#3a0a0c" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.68"/>
<polygon points="-0.4663,-0.0483 -0.9507,0.3094 -0.6988,-0.7085" fill="#b02821" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.74"/>
<polygon points="0.5531,0.1984 0.6988,0.7085 -0.1770,0.8699" fill="#3a0a0c" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.77"/>
<polygon points="-0.4663,-0.0483 -0.1770,0.8699 -0.9507,0.3094" fill="#681614" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.81"/>
<polygon points="0.5531,0.1984 0.2306,-0.7771 0.9507,-0.3094" fill="#5d1312" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.81"/>
<polygon points="-0.4663,-0.0483 -0.6988,-0.7085 0.2306,-0.7771" fill="#ca3d2f" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.85"/>
<polygon points="-0.4663,-0.0483 0.5531,0.1984 -0.1770,0.8699" fill="#611413" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.96"/>
<polygon points="-0.4663,-0.0483 0.2306,-0.7771 0.5531,0.1984" fill="#a3251e" stroke="#c9a84c" stroke-width="0.016" stroke-linejoin="round" stroke-opacity="0.98"/>
<text x="-0.7053" y="-0.1076" text-anchor="middle" font-family="Georgia, serif" font-weight="700" font-size="0.1153" fill="#f0d27a" fill-opacity="0.74">6</text>
<text x="0.3583" y="0.6353" text-anchor="middle" font-family="Georgia, serif" font-weight="700" font-size="0.1195" fill="#f0d27a" fill-opacity="0.77">16</text>
<text x="-0.5313" y="0.4218" text-anchor="middle" font-family="Georgia, serif" font-weight="700" font-size="0.1244" fill="#f0d27a" fill-opacity="0.81">4</text>
<text x="0.5782" y="-0.2513" text-anchor="middle" font-family="Georgia, serif" font-weight="700" font-size="0.1246" fill="#f0d27a" fill-opacity="0.81">8</text>
<text x="-0.3115" y="-0.4647" text-anchor="middle" font-family="Georgia, serif" font-weight="700" font-size="0.1295" fill="#f0d27a" fill-opacity="0.85">2</text>
<text x="-0.0300" y="0.3919" text-anchor="middle" font-family="Georgia, serif" font-weight="700" font-size="0.1442" fill="#f0d27a" fill-opacity="0.96">14</text>
<text x="0.1058" y="-0.0866" text-anchor="middle" font-family="'Cinzel Decorative', Georgia, serif" font-weight="700" font-size="0.3400" fill="#f0d27a" fill-opacity="1.00">20</text>`;

// A soft resin sheen over the whole die, clipped to its silhouette.
const SHEEN = `<polygon points="0.2306,-0.7771 0.1770,-0.8699 0.9507,-0.3094" fill="url(#d20-sheen)" /><polygon points="0.2306,-0.7771 -0.6988,-0.7085 0.1770,-0.8699" fill="url(#d20-sheen)" /><polygon points="0.5531,0.1984 0.9507,-0.3094 0.6988,0.7085" fill="url(#d20-sheen)" /><polygon points="-0.4663,-0.0483 -0.9507,0.3094 -0.6988,-0.7085" fill="url(#d20-sheen)" /><polygon points="0.5531,0.1984 0.6988,0.7085 -0.1770,0.8699" fill="url(#d20-sheen)" /><polygon points="-0.4663,-0.0483 -0.1770,0.8699 -0.9507,0.3094" fill="url(#d20-sheen)" /><polygon points="0.5531,0.1984 0.2306,-0.7771 0.9507,-0.3094" fill="url(#d20-sheen)" /><polygon points="-0.4663,-0.0483 -0.6988,-0.7085 0.2306,-0.7771" fill="url(#d20-sheen)" /><polygon points="-0.4663,-0.0483 0.5531,0.1984 -0.1770,0.8699" fill="url(#d20-sheen)" /><polygon points="-0.4663,-0.0483 0.2306,-0.7771 0.5531,0.1984" fill="url(#d20-sheen)" />`;
