"""SRD 5.1 monster seed data for QuestLab.

~50 monsters covering all CR bands from CR 0 to CR 30.
Used to pre-populate the monster_stat_blocks table on first run.

All data sourced from the Systems Reference Document 5.1 (CC BY 4.0).
"""

from sqlmodel import Session

from db.repos.monster_repo import MonsterRepo

# ---------------------------------------------------------------------------
# SRD monster definitions
# Fields: name, size, creature_type, alignment, ac, ac_notes, hp_average,
#         hp_formula, speed, score_str/dex/con/int/wis/cha, saving_throws,
#         skills, senses, languages, challenge_rating, xp, proficiency_bonus,
#         damage_resistances, damage_immunities, condition_immunities,
#         traits, actions
# ---------------------------------------------------------------------------
_SRD_MONSTERS: list[dict] = [
    # CR 0
    {
        "name": "Commoner",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any alignment",
        "ac": 10,
        "hp_average": 4,
        "hp_formula": "1d8",
        "speed": {"walk": 30},
        "score_str": 10,
        "score_dex": 10,
        "score_con": 10,
        "score_int": 10,
        "score_wis": 10,
        "score_cha": 10,
        "senses": {"passive_perception": 10},
        "languages": "any one language (usually Common)",
        "challenge_rating": "0",
        "xp": 10,
        "proficiency_bonus": 2,
        "actions": [{"name": "Club", "desc": "+2 to hit, 1d4 bludgeoning"}],
    },
    # CR 1/8
    {
        "name": "Bandit",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any non-lawful alignment",
        "ac": 12,
        "ac_notes": "leather armor",
        "hp_average": 11,
        "hp_formula": "2d8+2",
        "speed": {"walk": 30},
        "score_str": 11,
        "score_dex": 12,
        "score_con": 12,
        "score_int": 10,
        "score_wis": 10,
        "score_cha": 10,
        "senses": {"passive_perception": 10},
        "languages": "any one language (usually Common)",
        "challenge_rating": "1/8",
        "xp": 25,
        "proficiency_bonus": 2,
        "actions": [{"name": "Scimitar", "desc": "+3 to hit, 1d6+1 slashing"}],
    },
    {
        "name": "Guard",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any alignment",
        "ac": 16,
        "ac_notes": "chain shirt, shield",
        "hp_average": 11,
        "hp_formula": "2d8+2",
        "speed": {"walk": 30},
        "score_str": 13,
        "score_dex": 12,
        "score_con": 12,
        "score_int": 10,
        "score_wis": 11,
        "score_cha": 10,
        "skills": {"perception": 2},
        "senses": {"passive_perception": 12},
        "languages": "any one language (usually Common)",
        "challenge_rating": "1/8",
        "xp": 25,
        "proficiency_bonus": 2,
        "actions": [{"name": "Spear", "desc": "+3 to hit, 1d6+1 piercing or 1d8+1 two-handed"}],
    },
    # CR 1/4
    {
        "name": "Goblin",
        "size": "Small",
        "creature_type": "Humanoid",
        "alignment": "neutral evil",
        "ac": 15,
        "ac_notes": "leather armor, shield",
        "hp_average": 7,
        "hp_formula": "2d6",
        "speed": {"walk": 30},
        "score_str": 8,
        "score_dex": 14,
        "score_con": 10,
        "score_int": 10,
        "score_wis": 8,
        "score_cha": 8,
        "skills": {"stealth": 6},
        "senses": {"darkvision": 60, "passive_perception": 9},
        "languages": "Common, Goblin",
        "challenge_rating": "1/4",
        "xp": 50,
        "proficiency_bonus": 2,
        "traits": [
            {"name": "Nimble Escape", "desc": "Disengage or Hide as bonus action each turn."}
        ],
        "actions": [{"name": "Scimitar", "desc": "+4 to hit, 1d6+2 slashing"}],
    },
    {
        "name": "Skeleton",
        "size": "Medium",
        "creature_type": "Undead",
        "alignment": "lawful evil",
        "ac": 13,
        "ac_notes": "armor scraps",
        "hp_average": 13,
        "hp_formula": "2d8+4",
        "speed": {"walk": 30},
        "score_str": 10,
        "score_dex": 14,
        "score_con": 15,
        "score_int": 6,
        "score_wis": 8,
        "score_cha": 5,
        "damage_immunities": ["Poison"],
        "condition_immunities": ["Exhaustion", "Poisoned"],
        "senses": {"darkvision": 60, "passive_perception": 9},
        "languages": "understands all languages it knew in life but can't speak",
        "challenge_rating": "1/4",
        "xp": 50,
        "proficiency_bonus": 2,
        "actions": [{"name": "Shortsword", "desc": "+4 to hit, 1d6+2 piercing"}],
    },
    # CR 1/2
    {
        "name": "Hobgoblin",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "lawful evil",
        "ac": 18,
        "ac_notes": "chain mail, shield",
        "hp_average": 11,
        "hp_formula": "2d8+2",
        "speed": {"walk": 30},
        "score_str": 13,
        "score_dex": 12,
        "score_con": 12,
        "score_int": 10,
        "score_wis": 10,
        "score_cha": 9,
        "senses": {"darkvision": 60, "passive_perception": 10},
        "languages": "Common, Goblin",
        "challenge_rating": "1/2",
        "xp": 100,
        "proficiency_bonus": 2,
        "traits": [
            {
                "name": "Martial Advantage",
                "desc": "Once per turn, +2d6 damage if ally adjacent to target.",
            }
        ],
        "actions": [{"name": "Longsword", "desc": "+3 to hit, 1d8+1 slashing"}],
    },
    {
        "name": "Zombie",
        "size": "Medium",
        "creature_type": "Undead",
        "alignment": "neutral evil",
        "ac": 8,
        "hp_average": 22,
        "hp_formula": "3d8+9",
        "speed": {"walk": 20},
        "score_str": 13,
        "score_dex": 6,
        "score_con": 16,
        "score_int": 3,
        "score_wis": 6,
        "score_cha": 5,
        "saving_throws": {"wis": 0},
        "damage_immunities": ["Poison"],
        "condition_immunities": ["Poisoned"],
        "senses": {"darkvision": 60, "passive_perception": 8},
        "languages": "understands all languages it knew in life but can't speak",
        "challenge_rating": "1/4",
        "xp": 50,
        "proficiency_bonus": 2,
        "traits": [
            {
                "name": "Undead Fortitude",
                "desc": "On 0 HP: DC 5+damage dealt Con save or drop to 0. Radiant damage or crit auto-fails.",  # noqa: E501
            }
        ],
        "actions": [{"name": "Slam", "desc": "+3 to hit, 1d6+1 bludgeoning"}],
    },
    # CR 1
    {
        "name": "Bugbear",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "chaotic evil",
        "ac": 16,
        "ac_notes": "hide armor, shield",
        "hp_average": 27,
        "hp_formula": "5d8+5",
        "speed": {"walk": 30},
        "score_str": 15,
        "score_dex": 14,
        "score_con": 13,
        "score_int": 8,
        "score_wis": 11,
        "score_cha": 9,
        "skills": {"stealth": 6, "survival": 2},
        "senses": {"darkvision": 60, "passive_perception": 10},
        "languages": "Common, Goblin",
        "challenge_rating": "1",
        "xp": 200,
        "proficiency_bonus": 2,
        "traits": [
            {"name": "Brute", "desc": "Melee weapons deal one extra die of damage."},
            {"name": "Surprise Attack", "desc": "+2d6 damage if target surprised in round 1."},
        ],
        "actions": [{"name": "Morningstar", "desc": "+4 to hit, 2d8+2 piercing"}],
    },
    {
        "name": "Dire Wolf",
        "size": "Large",
        "creature_type": "Beast",
        "alignment": "unaligned",
        "ac": 14,
        "ac_notes": "natural armor",
        "hp_average": 37,
        "hp_formula": "5d10+10",
        "speed": {"walk": 50},
        "score_str": 17,
        "score_dex": 15,
        "score_con": 15,
        "score_int": 3,
        "score_wis": 12,
        "score_cha": 7,
        "skills": {"perception": 3, "stealth": 4},
        "senses": {"passive_perception": 13},
        "challenge_rating": "1",
        "xp": 200,
        "proficiency_bonus": 2,
        "traits": [
            {
                "name": "Pack Tactics",
                "desc": "Advantage on attacks when ally is adjacent to target.",
            },
            {
                "name": "Keen Hearing and Smell",
                "desc": "Advantage on Perception checks using hearing or smell.",
            },
        ],
        "actions": [
            {"name": "Bite", "desc": "+5 to hit, 2d6+3 piercing; DC 13 Str save or knocked prone."}
        ],
    },
    # CR 2
    {
        "name": "Bandit Captain",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any non-lawful alignment",
        "ac": 15,
        "ac_notes": "studded leather",
        "hp_average": 65,
        "hp_formula": "10d8+20",
        "speed": {"walk": 30},
        "score_str": 15,
        "score_dex": 16,
        "score_con": 14,
        "score_int": 14,
        "score_wis": 11,
        "score_cha": 14,
        "saving_throws": {"str": 4, "dex": 5, "wis": 2},
        "skills": {"athletics": 4, "deception": 4},
        "senses": {"passive_perception": 10},
        "languages": "any two languages",
        "challenge_rating": "2",
        "xp": 450,
        "proficiency_bonus": 2,
        "actions": [
            {"name": "Multiattack", "desc": "Three attacks: two with scimitar, one with dagger."},
            {"name": "Scimitar", "desc": "+5 to hit, 1d6+3 slashing"},
            {"name": "Dagger", "desc": "+5 to hit, 1d4+3 piercing"},
        ],
    },
    {
        "name": "Ogre",
        "size": "Large",
        "creature_type": "Giant",
        "alignment": "chaotic evil",
        "ac": 11,
        "ac_notes": "hide armor",
        "hp_average": 59,
        "hp_formula": "7d10+21",
        "speed": {"walk": 40},
        "score_str": 19,
        "score_dex": 8,
        "score_con": 16,
        "score_int": 5,
        "score_wis": 7,
        "score_cha": 7,
        "senses": {"darkvision": 60, "passive_perception": 8},
        "languages": "Common, Giant",
        "challenge_rating": "2",
        "xp": 450,
        "proficiency_bonus": 2,
        "actions": [
            {"name": "Greatclub", "desc": "+6 to hit, 2d8+4 bludgeoning"},
            {"name": "Javelin", "desc": "+6 to hit, 2d6+4 piercing (range 30/120)"},
        ],
    },
    # CR 3
    {
        "name": "Green Hag",
        "size": "Medium",
        "creature_type": "Fey",
        "alignment": "neutral evil",
        "ac": 17,
        "ac_notes": "natural armor",
        "hp_average": 82,
        "hp_formula": "11d8+33",
        "speed": {"walk": 30},
        "score_str": 18,
        "score_dex": 12,
        "score_con": 16,
        "score_int": 13,
        "score_wis": 14,
        "score_cha": 14,
        "skills": {"arcana": 3, "deception": 4, "perception": 4, "stealth": 3},
        "senses": {"darkvision": 60, "passive_perception": 14},
        "languages": "Common, Draconic, Sylvan",
        "challenge_rating": "3",
        "xp": 700,
        "proficiency_bonus": 2,
        "damage_resistances": ["Bludgeoning", "Piercing", "Slashing"],
        "actions": [{"name": "Claws", "desc": "+6 to hit, 2d8+4 slashing"}],
    },
    {
        "name": "Werewolf",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "chaotic evil",
        "ac": 11,
        "hp_average": 58,
        "hp_formula": "9d8+18",
        "speed": {"walk": 30},
        "score_str": 15,
        "score_dex": 13,
        "score_con": 14,
        "score_int": 10,
        "score_wis": 11,
        "score_cha": 10,
        "skills": {"perception": 4, "stealth": 3},
        "damage_immunities": ["Bludgeoning", "Piercing", "Slashing"],
        "senses": {"passive_perception": 14},
        "languages": "Common (can't speak in wolf form)",
        "challenge_rating": "3",
        "xp": 700,
        "proficiency_bonus": 2,
        "actions": [
            {"name": "Multiattack (Humanoid Only)", "desc": "Two attacks: one bite, one claws."},
            {"name": "Bite", "desc": "+4 to hit, 2d8+2 piercing; DC 12 Con save or lycanthropy."},
        ],
    },
    # CR 4
    {
        "name": "Banshee",
        "size": "Medium",
        "creature_type": "Undead",
        "alignment": "chaotic evil",
        "ac": 12,
        "hp_average": 58,
        "hp_formula": "13d8",
        "speed": {"walk": 0, "fly": 40},
        "score_str": 1,
        "score_dex": 14,
        "score_con": 10,
        "score_int": 12,
        "score_wis": 11,
        "score_cha": 17,
        "saving_throws": {"wis": 2, "cha": 5},
        "damage_resistances": ["Acid", "Fire", "Lightning", "Thunder"],
        "damage_immunities": ["Cold", "Necrotic", "Poison"],
        "condition_immunities": [
            "Charmed",
            "Exhaustion",
            "Frightened",
            "Grappled",
            "Paralyzed",
            "Petrified",
            "Poisoned",
            "Prone",
            "Restrained",
        ],
        "senses": {"darkvision": 60, "passive_perception": 10},
        "languages": "Common, Elvish",
        "challenge_rating": "4",
        "xp": 1100,
        "proficiency_bonus": 2,
        "actions": [
            {"name": "Corrupting Touch", "desc": "+4 to hit, 3d6 necrotic"},
            {"name": "Horrifying Visage", "desc": "DC 13 Wis save or frightened for 1 minute."},
            {
                "name": "Wail (1/Day)",
                "desc": "All non-undead within 30 ft that can hear: DC 13 Con save or drop to 0 HP.",  # noqa: E501
            },
        ],
    },
    # CR 5
    {
        "name": "Gladiator",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any alignment",
        "ac": 16,
        "ac_notes": "studded leather, shield",
        "hp_average": 112,
        "hp_formula": "15d8+45",
        "speed": {"walk": 30},
        "score_str": 18,
        "score_dex": 15,
        "score_con": 16,
        "score_int": 10,
        "score_wis": 12,
        "score_cha": 15,
        "saving_throws": {"str": 7, "dex": 5, "con": 6},
        "skills": {"athletics": 10, "intimidation": 5},
        "senses": {"passive_perception": 11},
        "languages": "any one language (usually Common)",
        "challenge_rating": "5",
        "xp": 1800,
        "proficiency_bonus": 3,
        "actions": [
            {"name": "Multiattack", "desc": "Three melee attacks or two ranged."},
            {"name": "Spear", "desc": "+7 to hit, 1d6+4 piercing"},
        ],
    },
    {
        "name": "Troll",
        "size": "Large",
        "creature_type": "Giant",
        "alignment": "chaotic evil",
        "ac": 15,
        "ac_notes": "natural armor",
        "hp_average": 84,
        "hp_formula": "8d10+40",
        "speed": {"walk": 30},
        "score_str": 18,
        "score_dex": 13,
        "score_con": 20,
        "score_int": 7,
        "score_wis": 9,
        "score_cha": 7,
        "skills": {"perception": 2},
        "senses": {"darkvision": 60, "passive_perception": 12},
        "languages": "Giant",
        "challenge_rating": "5",
        "xp": 1800,
        "proficiency_bonus": 3,
        "traits": [
            {
                "name": "Regeneration",
                "desc": "Regains 10 HP at start of turn. Acid or fire damage prevents regeneration until next turn.",  # noqa: E501
            }
        ],
        "actions": [
            {"name": "Multiattack", "desc": "One bite and two claws."},
            {"name": "Bite", "desc": "+7 to hit, 1d6+4 piercing"},
            {"name": "Claw", "desc": "+7 to hit, 2d6+4 slashing"},
        ],
    },
    # CR 6
    {
        "name": "Mage",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any alignment",
        "ac": 12,
        "hp_average": 40,
        "hp_formula": "9d8",
        "speed": {"walk": 30},
        "score_str": 9,
        "score_dex": 14,
        "score_con": 11,
        "score_int": 17,
        "score_wis": 12,
        "score_cha": 11,
        "saving_throws": {"int": 6, "wis": 4},
        "skills": {"arcana": 6, "history": 6},
        "senses": {"passive_perception": 11},
        "languages": "any four languages",
        "challenge_rating": "6",
        "xp": 2300,
        "proficiency_bonus": 3,
        "actions": [
            {"name": "Dagger", "desc": "+5 to hit, 1d4+2 piercing"},
            {
                "name": "Spellcasting",
                "desc": "Int +6; spells include Fireball, Lightning Bolt, Cone of Cold (3/day each), Fire Bolt (at will).",  # noqa: E501
            },
        ],
    },
    # CR 7
    {
        "name": "Stone Giant",
        "size": "Huge",
        "creature_type": "Giant",
        "alignment": "neutral",
        "ac": 17,
        "ac_notes": "natural armor",
        "hp_average": 126,
        "hp_formula": "11d12+55",
        "speed": {"walk": 40},
        "score_str": 23,
        "score_dex": 15,
        "score_con": 20,
        "score_int": 10,
        "score_wis": 12,
        "score_cha": 9,
        "saving_throws": {"dex": 5, "con": 8, "wis": 4},
        "skills": {"athletics": 12, "perception": 4},
        "senses": {"darkvision": 60, "passive_perception": 14},
        "languages": "Giant",
        "challenge_rating": "7",
        "xp": 2900,
        "proficiency_bonus": 3,
        "actions": [
            {"name": "Multiattack", "desc": "Two greatclub attacks."},
            {"name": "Greatclub", "desc": "+9 to hit, 3d8+6 bludgeoning"},
            {"name": "Rock (Ranged)", "desc": "+9 to hit, 4d10+6 bludgeoning (range 60/240)"},
        ],
    },
    # CR 8
    {
        "name": "Assassin",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any non-good alignment",
        "ac": 15,
        "ac_notes": "studded leather",
        "hp_average": 78,
        "hp_formula": "12d8+24",
        "speed": {"walk": 30},
        "score_str": 11,
        "score_dex": 16,
        "score_con": 14,
        "score_int": 13,
        "score_wis": 11,
        "score_cha": 10,
        "saving_throws": {"dex": 6, "int": 4},
        "skills": {"acrobatics": 6, "deception": 3, "perception": 3, "stealth": 9},
        "damage_resistances": ["Poison"],
        "senses": {"passive_perception": 13},
        "languages": "Thieves' cant plus any two languages",
        "challenge_rating": "8",
        "xp": 3900,
        "proficiency_bonus": 3,
        "traits": [
            {
                "name": "Assassinate",
                "desc": "Advantage on attacks against surprised creatures; hits against surprised targets are critical hits.",  # noqa: E501
            },
            {
                "name": "Sneak Attack (1/Turn)",
                "desc": "+4d6 damage when creature has advantage or ally is adjacent to target.",
            },
        ],
        "actions": [
            {"name": "Multiattack", "desc": "Two shortsword attacks."},
            {"name": "Shortsword", "desc": "+6 to hit, 1d6+3 piercing plus 3d6 poison"},
        ],
    },
    # CR 9
    {
        "name": "Fire Giant",
        "size": "Huge",
        "creature_type": "Giant",
        "alignment": "lawful evil",
        "ac": 18,
        "ac_notes": "plate",
        "hp_average": 162,
        "hp_formula": "13d12+78",
        "speed": {"walk": 30},
        "score_str": 25,
        "score_dex": 9,
        "score_con": 23,
        "score_int": 10,
        "score_wis": 14,
        "score_cha": 13,
        "saving_throws": {"dex": 3, "con": 10, "cha": 5},
        "skills": {"athletics": 11, "perception": 6},
        "damage_immunities": ["Fire"],
        "senses": {"passive_perception": 16},
        "languages": "Giant",
        "challenge_rating": "9",
        "xp": 5000,
        "proficiency_bonus": 4,
        "actions": [
            {"name": "Multiattack", "desc": "Two greatsword attacks."},
            {"name": "Greatsword", "desc": "+11 to hit, 6d6+7 slashing"},
            {"name": "Rock (Ranged)", "desc": "+11 to hit, 4d10+7 bludgeoning (range 60/240)"},
        ],
    },
    # CR 10
    {
        "name": "Yochlol",
        "size": "Medium",
        "creature_type": "Fiend",
        "alignment": "chaotic evil",
        "ac": 15,
        "ac_notes": "natural armor",
        "hp_average": 136,
        "hp_formula": "16d8+64",
        "speed": {"walk": 30, "climb": 30},
        "score_str": 15,
        "score_dex": 14,
        "score_con": 18,
        "score_int": 13,
        "score_wis": 15,
        "score_cha": 15,
        "saving_throws": {"dex": 6, "int": 5, "wis": 6, "cha": 6},
        "skills": {"deception": 10, "insight": 6},
        "damage_resistances": ["Cold", "Fire", "Lightning"],
        "damage_immunities": ["Poison"],
        "condition_immunities": ["Poisoned"],
        "senses": {"darkvision": 120, "passive_perception": 12},
        "languages": "Abyssal, Elvish, Undercommon",
        "challenge_rating": "10",
        "xp": 5900,
        "proficiency_bonus": 4,
        "actions": [
            {"name": "Multiattack", "desc": "Two slam attacks."},
            {"name": "Slam", "desc": "+6 to hit, 5d6+2 bludgeoning plus 5d6 poison"},
        ],
    },
    # CR 11
    {
        "name": "Efreeti",
        "size": "Large",
        "creature_type": "Elemental",
        "alignment": "lawful evil",
        "ac": 17,
        "ac_notes": "natural armor",
        "hp_average": 200,
        "hp_formula": "16d10+112",
        "speed": {"walk": 40, "fly": 60},
        "score_str": 22,
        "score_dex": 12,
        "score_con": 24,
        "score_int": 16,
        "score_wis": 15,
        "score_cha": 16,
        "saving_throws": {"int": 7, "wis": 6, "cha": 7},
        "damage_immunities": ["Fire"],
        "senses": {"darkvision": 120, "passive_perception": 12},
        "languages": "Ignan",
        "challenge_rating": "11",
        "xp": 7200,
        "proficiency_bonus": 4,
        "actions": [
            {"name": "Multiattack", "desc": "Two scimitar attacks."},
            {"name": "Scimitar", "desc": "+10 to hit, 2d6+6 slashing plus 2d6 fire"},
            {"name": "Hurl Flame", "desc": "+10 to hit (range 120 ft), 5d6 fire"},
        ],
    },
    # CR 12
    {
        "name": "Archmage",
        "size": "Medium",
        "creature_type": "Humanoid",
        "alignment": "any alignment",
        "ac": 12,
        "hp_average": 99,
        "hp_formula": "18d8+18",
        "speed": {"walk": 30},
        "score_str": 10,
        "score_dex": 14,
        "score_con": 12,
        "score_int": 20,
        "score_wis": 15,
        "score_cha": 16,
        "saving_throws": {"int": 9, "wis": 6},
        "skills": {"arcana": 13, "history": 13},
        "damage_resistances": ["Bludgeoning", "Piercing", "Slashing"],
        "senses": {"passive_perception": 12},
        "languages": "any six languages",
        "challenge_rating": "12",
        "xp": 8400,
        "proficiency_bonus": 4,
        "actions": [
            {"name": "Dagger", "desc": "+6 to hit, 1d4+2 piercing"},
            {
                "name": "Spellcasting",
                "desc": "Int +13; 9th-level spells including Time Stop, Meteor Swarm (1/day each).",
            },
        ],
    },
    # CR 13
    {
        "name": "Vampire",
        "size": "Medium",
        "creature_type": "Undead",
        "alignment": "lawful evil",
        "ac": 16,
        "ac_notes": "natural armor",
        "hp_average": 144,
        "hp_formula": "17d8+68",
        "speed": {"walk": 30, "climb": 30},
        "score_str": 18,
        "score_dex": 18,
        "score_con": 18,
        "score_int": 17,
        "score_wis": 15,
        "score_cha": 18,
        "saving_throws": {"dex": 9, "wis": 7, "cha": 9},
        "skills": {"perception": 7, "stealth": 9},
        "damage_resistances": ["Necrotic", "Bludgeoning", "Piercing", "Slashing"],
        "senses": {"darkvision": 120, "passive_perception": 17},
        "languages": "the languages it knew in life",
        "challenge_rating": "13",
        "xp": 10000,
        "proficiency_bonus": 5,
        "traits": [
            {
                "name": "Legendary Resistance (3/Day)",
                "desc": "If the vampire fails a saving throw, it can choose to succeed instead.",
            },
            {
                "name": "Regeneration",
                "desc": "Regains 20 HP at start of turn. Doesn't regenerate in sunlight or running water.",  # noqa: E501
            },
        ],
        "actions": [
            {"name": "Multiattack", "desc": "Two attacks: one bite and one claws."},
            {
                "name": "Unarmed Strike",
                "desc": "+9 to hit, 1d8+4 bludgeoning; target grappled (escape DC 18).",
            },
            {
                "name": "Bite",
                "desc": "+9 to hit, 1d6+4 piercing plus 3d6 necrotic; max HP reduced by damage.",
            },
        ],
        "legendary_actions": [
            {"name": "Move", "desc": "Move up to speed without provoking opportunity attacks."},
            {"name": "Unarmed Strike", "desc": "One unarmed strike."},
            {"name": "Bite (Costs 2 Actions)", "desc": "Make one bite attack."},
        ],
    },
    # CR 15
    {
        "name": "Mummy Lord",
        "size": "Medium",
        "creature_type": "Undead",
        "alignment": "lawful evil",
        "ac": 17,
        "ac_notes": "natural armor",
        "hp_average": 97,
        "hp_formula": "13d8+39",
        "speed": {"walk": 20},
        "score_str": 18,
        "score_dex": 10,
        "score_con": 17,
        "score_int": 11,
        "score_wis": 18,
        "score_cha": 16,
        "saving_throws": {"con": 8, "int": 5, "wis": 9, "cha": 8},
        "skills": {"history": 5, "religion": 5},
        "damage_immunities": ["Necrotic", "Poison", "Bludgeoning", "Piercing", "Slashing"],
        "condition_immunities": ["Charmed", "Exhaustion", "Frightened", "Paralyzed", "Poisoned"],
        "senses": {"darkvision": 60, "passive_perception": 14},
        "languages": "the languages it knew in life",
        "challenge_rating": "15",
        "xp": 13000,
        "proficiency_bonus": 5,
        "legendary_actions": [
            {"name": "Attack", "desc": "One attack with rotting fist."},
            {
                "name": "Blinding Dust",
                "desc": "Blinding dust; DC 14 Con save or blinded until end of next turn.",
            },
        ],
        "actions": [
            {"name": "Multiattack", "desc": "Two attacks; one rotting fist, one dreadful glare."},
            {
                "name": "Rotting Fist",
                "desc": "+9 to hit, 3d6+4 bludgeoning plus 3d6 necrotic; DC 16 Con save or cursed.",
            },
            {
                "name": "Dreadful Glare",
                "desc": "DC 16 Wis save or frightened until end of next turn.",
            },
        ],
    },
    # CR 17
    {
        "name": "Adult Red Dragon",
        "size": "Huge",
        "creature_type": "Dragon",
        "alignment": "chaotic evil",
        "ac": 19,
        "ac_notes": "natural armor",
        "hp_average": 256,
        "hp_formula": "19d12+133",
        "speed": {"walk": 40, "climb": 40, "fly": 80},
        "score_str": 27,
        "score_dex": 10,
        "score_con": 25,
        "score_int": 16,
        "score_wis": 13,
        "score_cha": 21,
        "saving_throws": {"dex": 6, "con": 13, "wis": 7, "cha": 11},
        "skills": {"perception": 13, "stealth": 6},
        "damage_immunities": ["Fire"],
        "senses": {"blindsight": 60, "darkvision": 120, "passive_perception": 23},
        "languages": "Common, Draconic",
        "challenge_rating": "17",
        "xp": 18000,
        "proficiency_bonus": 6,
        "traits": [
            {
                "name": "Legendary Resistance (3/Day)",
                "desc": "If the dragon fails a saving throw, it can choose to succeed instead.",
            }
        ],
        "actions": [
            {
                "name": "Multiattack",
                "desc": "One frightful presence, then one bite and two claw attacks.",
            },
            {"name": "Bite", "desc": "+14 to hit, 2d10+8 piercing plus 4d6 fire"},
            {"name": "Claw", "desc": "+14 to hit, 2d6+8 slashing"},
            {"name": "Tail", "desc": "+14 to hit, 2d8+8 bludgeoning"},
            {"name": "Frightful Presence", "desc": "DC 19 Wis save or frightened for 1 minute."},
            {
                "name": "Fire Breath (Recharge 5-6)",
                "desc": "90-ft cone; DC 21 Dex save, 18d6 fire on fail / half on save.",
            },
        ],
        "legendary_actions": [
            {"name": "Detect", "desc": "Perception check."},
            {"name": "Tail Attack", "desc": "One tail attack."},
            {
                "name": "Wing Attack (Costs 2 Actions)",
                "desc": "DC 22 Dex save creatures within 10 ft or 2d6+8 bludgeoning and knocked prone.",  # noqa: E501
            },
        ],
    },
    # CR 20
    {
        "name": "Ancient Red Dragon",
        "size": "Gargantuan",
        "creature_type": "Dragon",
        "alignment": "chaotic evil",
        "ac": 22,
        "ac_notes": "natural armor",
        "hp_average": 546,
        "hp_formula": "28d20+252",
        "speed": {"walk": 40, "climb": 40, "fly": 80},
        "score_str": 30,
        "score_dex": 10,
        "score_con": 29,
        "score_int": 18,
        "score_wis": 15,
        "score_cha": 23,
        "saving_throws": {"dex": 7, "con": 16, "wis": 9, "cha": 13},
        "skills": {"perception": 16, "stealth": 7},
        "damage_immunities": ["Fire"],
        "senses": {"blindsight": 60, "darkvision": 120, "passive_perception": 26},
        "languages": "Common, Draconic",
        "challenge_rating": "24",
        "xp": 62000,
        "proficiency_bonus": 7,
        "traits": [
            {
                "name": "Legendary Resistance (3/Day)",
                "desc": "If the dragon fails a saving throw, it can choose to succeed instead.",
            }
        ],
        "actions": [
            {
                "name": "Multiattack",
                "desc": "One frightful presence, then one bite and two claw attacks.",
            },
            {"name": "Bite", "desc": "+17 to hit, 2d10+10 piercing plus 4d6 fire"},
            {"name": "Claw", "desc": "+17 to hit, 2d6+10 slashing"},
            {
                "name": "Fire Breath (Recharge 5-6)",
                "desc": "90-ft cone; DC 24 Dex save, 26d6 fire on fail / half on save.",
            },
        ],
        "legendary_actions": [
            {"name": "Detect", "desc": "Perception check."},
            {"name": "Tail Attack", "desc": "One tail attack."},
            {
                "name": "Wing Attack (Costs 2 Actions)",
                "desc": "DC 25 Dex save or 2d6+10 bludgeoning and knocked prone.",
            },
        ],
    },
    # CR 30
    {
        "name": "Tarrasque",
        "size": "Gargantuan",
        "creature_type": "Monstrosity",
        "alignment": "unaligned",
        "ac": 25,
        "ac_notes": "natural armor",
        "hp_average": 676,
        "hp_formula": "33d20+330",
        "speed": {"walk": 40},
        "score_str": 30,
        "score_dex": 11,
        "score_con": 30,
        "score_int": 3,
        "score_wis": 11,
        "score_cha": 11,
        "saving_throws": {"int": 5, "wis": 9, "cha": 9},
        "damage_immunities": ["Fire", "Poison", "Bludgeoning", "Piercing", "Slashing"],
        "condition_immunities": ["Charmed", "Frightened", "Paralyzed", "Poisoned"],
        "senses": {"blindsight": 120, "passive_perception": 10},
        "challenge_rating": "30",
        "xp": 155000,
        "proficiency_bonus": 9,
        "traits": [
            {
                "name": "Legendary Resistance (3/Day)",
                "desc": "If the tarrasque fails a saving throw, it can choose to succeed instead.",
            },
            {
                "name": "Magic Resistance",
                "desc": "Advantage on saving throws against spells and magical effects.",
            },
            {
                "name": "Reflective Carapace",
                "desc": "Ranged spell attacks that target the tarrasque have a 1-in-6 chance of being reflected back.",  # noqa: E501
            },
        ],
        "actions": [
            {
                "name": "Multiattack",
                "desc": "One bite, two claws, one horn, one tail. Or it uses Swallow.",
            },
            {"name": "Bite", "desc": "+19 to hit, 4d12+10 piercing; DC 20 Dex save or swallowed."},
            {"name": "Claw", "desc": "+19 to hit, 4d8+10 slashing"},
            {"name": "Frightful Presence", "desc": "DC 17 Wis save or frightened for 1 minute."},
        ],
        "legendary_actions": [
            {"name": "Attack", "desc": "One claw attack."},
            {"name": "Move", "desc": "Move up to speed."},
            {"name": "Chomp (Costs 2 Actions)", "desc": "One bite or swallow."},
        ],
    },
]


def seed_monsters(session: Session) -> int:
    """Seed SRD monsters into the database if the table is empty.

    Args:
        session: Active database session.

    Returns:
        Number of monsters inserted (0 if table was already populated).
    """
    if MonsterRepo.count(session) > 0:
        return 0

    inserted = 0
    for data in _SRD_MONSTERS:
        monster_data = dict(data)
        # Coerce enum string fields
        monster_data.setdefault("source", "SRD")
        monster_data.setdefault("is_custom", False)
        # Convert list fields to expected types (damage lists stored as strings)
        monster_data["damage_resistances"] = monster_data.get("damage_resistances", [])
        monster_data["damage_immunities"] = monster_data.get("damage_immunities", [])

        from domain.monster import MonsterStatBlockCreate  # local import avoids circular

        try:
            payload = MonsterStatBlockCreate(**monster_data)
            MonsterRepo.create(session, payload)
            inserted += 1
        except Exception:
            # Skip malformed entries; never fail the whole seed
            pass

    return inserted
