"""Wire the temple crawl for players: room maps + the Tide Gate puzzle.

Uploads the five room maps (generated by gen_session5_room_maps.py) into
the battle-map library and seeds one more Puzzle Workbench board:

  THE TIDE GATE — a four-tile glyph board ⬟ ● ◼ ✱ answering HOLD.
  Backup only: the room now runs from one static image, solved out loud.
  No pre-known letters: the table earned this entire alphabet decoding
  COME HOME, CHILD in Session 4 — pressing the door's tiles is them
  proving it. Wrong spoken reading = the water SLAPS (the hum counter
  is the DM's cue). The player link goes on the projector like the
  Refrain did.

Idempotent: existing maps/puzzles with the same names are skipped.

Usage:
    python scripts/seed_session5_room_maps.py --dm-email you@example.com
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))

import httpx  # noqa: E402

from scripts.gen_session5_room_maps import ROOMS  # noqa: E402

DEFAULT_API_BASE = "https://questlab-api-9yhe.onrender.com/api"
DEFAULT_CAMPAIGN_ID = "80b6f517-d124-4fea-9435-8e727f3171a9"
AUTH_HEADER = "X-MS-CLIENT-PRINCIPAL-NAME"
WIDTH, HEIGHT = 1536, 1024
GRID = 64  # 5-ft squares, same as the rest of the Session 5 set

# Same glyph ids as the Session 4 seed (C=g1 O=g2 M=g3 E=g4 H=g5 …), so the
# workbench renders the exact shapes the table already knows.
TIDE_GATE_PUZZLE = {
    "kind": "glyph",
    "title": "The Tide Gate",
    "config": {
        "tokens": ["g5", "g2", "g7", "g8"],  # ⬟ ● ◼ ✱ = H O L D
        "mapping": {"g5": "H", "g2": "O", "g7": "L", "g8": "D"},
        "preknown": {},  # they EARNED this alphabet — no free letters
        "answer": "HOLD",
        "hide_spaces": True,
    },
}


def main() -> int:
    """Upload room maps and seed the Tide Gate board."""
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--api-base", default=DEFAULT_API_BASE)
    parser.add_argument("--campaign-id", default=DEFAULT_CAMPAIGN_ID)
    parser.add_argument("--dm-email", required=True)
    args = parser.parse_args()

    headers = {AUTH_HEADER: args.dm_email}

    # ── Maps ──────────────────────────────────────────────────────────────
    existing = httpx.get(
        f"{args.api_base}/campaigns/{args.campaign_id}/battle-maps",
        headers=headers,
        timeout=60.0,
    )
    existing.raise_for_status()
    have = {m["name"] for m in existing.json()}

    for slug, (name, _scene) in ROOMS.items():
        if name in have:
            print(f"  · '{name}' already in the library — skipped")
            continue
        png = _ROOT / "data" / "generated-maps" / f"{slug}.png"
        if not png.exists():
            print(f"  ✗ {png.name} missing — run gen_session5_room_maps.py first")
            return 1
        data = png.read_bytes()
        print(f"Uploading {png.name} ({len(data) // 1024} KB) …")
        resp = httpx.post(
            f"{args.api_base}/uploads/map",
            headers=headers,
            files={"file": (png.name, data, "image/png")},
            timeout=180.0,
        )
        resp.raise_for_status()
        resp = httpx.post(
            f"{args.api_base}/campaigns/{args.campaign_id}/battle-maps",
            headers=headers,
            json={
                "name": name,
                "image_url": resp.json()["url"],
                "width": WIDTH,
                "height": HEIGHT,
                "grid_size": GRID,
            },
            timeout=60.0,
        )
        resp.raise_for_status()
        print(f"  ✓ '{name}' created")

    # ── The Tide Gate puzzle ──────────────────────────────────────────────
    puzzles = httpx.get(
        f"{args.api_base}/campaigns/{args.campaign_id}/puzzles",
        headers=headers,
        timeout=60.0,
    )
    puzzles.raise_for_status()
    if any(p["title"] == TIDE_GATE_PUZZLE["title"] for p in puzzles.json()):
        print("  · Tide Gate puzzle already seeded — skipped")
    else:
        resp = httpx.post(
            f"{args.api_base}/campaigns/{args.campaign_id}/puzzles",
            headers=headers,
            json=TIDE_GATE_PUZZLE,
            timeout=60.0,
        )
        resp.raise_for_status()
        pid = resp.json()["id"]
        print(f"  ✓ Tide Gate glyph board seeded — player link: /puzzle/{pid}")

    print("\nDone. Re-import campaigns/session-05-scenes.json on the board for the room scenes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
