"""Wire Session 6 ("Into the Fey", Plan 00059): boards + token tray.

1. Uploads the four boards (generated by gen_session6_boards.py) into the
   battle-map library.
2. Ensures the Session 6 row on the adventure.
3. Generates minifig token figures via the app's own /table/figure lane
   for the creatures the handoff DESCRIBES (nothing invented), and parks
   them as an UNLABELED token tray along the top edge of the session's
   table — boards are shared screens, so no token carries a label.

Named allies get no pre-generated figures (the handoff gives them no
visual description); the DM generates those in-app or uses NPC portraits.

Idempotent: existing maps are skipped by name; the tray is skipped if any
tray token id is already present; the session row is only created if
session 6 is absent.

Usage:
    python scripts/seed_session6_boards.py --dm-email you@example.com --dry-run
    python scripts/seed_session6_boards.py --dm-email you@example.com
    python scripts/seed_session6_boards.py --dm-email you@example.com --skip-figures
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))

import httpx  # noqa: E402

from scripts.gen_session6_boards import BOARDS  # noqa: E402

DEFAULT_API_BASE = "https://questlab-api-9yhe.onrender.com/api"
DEFAULT_CAMPAIGN_ID = "80b6f517-d124-4fea-9435-8e727f3171a9"
DEFAULT_ADVENTURE_ID = "ee3d7a70-4a01-4b9b-b026-f5415146b3bc"
AUTH_HEADER = "X-MS-CLIENT-PRINCIPAL-NAME"
WIDTH, HEIGHT = 1536, 1024
GRID = 64  # 5-ft squares, same convention as the Session 5 set

SESSION_NUMBER = 6
SESSION_TITLE = "Into the Fey"  # from the handoff header

# Token figures — ONLY creatures the handoff describes. name feeds the
# minifig generator; label on the board stays EMPTY (shared screen).
# size in grid squares (Large = 2).
FIGURES: list[dict] = [
    {"id": "s6-boss", "name": "tall wood elf woman in gray", "size": 1.0},
    {"id": "s6-driftwood", "name": "knee-high driftwood creature", "size": 0.5},
    {"id": "s6-staff-1", "name": "wood elf bathhouse attendant", "size": 1.0},
    {"id": "s6-staff-2", "name": "wood elf bathhouse attendant", "size": 1.0},
    {"id": "s6-staff-3", "name": "wood elf bathhouse attendant", "size": 1.0},
    {
        "id": "s6-champion",
        "name": "snapping turtle creature the size of a door, standing upright",
        "size": 2.0,
    },
    {"id": "s6-octopus", "name": "giant octopus", "size": 2.0},
    {"id": "s6-plesiosaur", "name": "plesiosaurus, long-necked sea reptile", "size": 2.0},
    {"id": "s6-shark", "name": "hunter shark, dorsal fin above the water", "size": 2.0},
    {"id": "s6-bigshark", "name": "enormous great shark, much larger", "size": 3.0},
    {"id": "s6-seahorse-1", "name": "giant sea horse", "size": 2.0},
    {"id": "s6-seahorse-2", "name": "giant sea horse", "size": 2.0},
    {"id": "s6-seahorse-3", "name": "giant sea horse", "size": 2.0},
    {"id": "s6-seaturtle", "name": "big sea turtle", "size": 2.0},
    {"id": "s6-crab-1", "name": "small crab creature", "size": 0.5},
    {"id": "s6-crab-2", "name": "small crab creature", "size": 0.5},
    {"id": "s6-crab-3", "name": "small crab creature", "size": 0.5},
]


def main() -> int:
    """Upload boards, ensure the session, generate + park the token tray."""
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--api-base", default=DEFAULT_API_BASE)
    parser.add_argument("--campaign-id", default=DEFAULT_CAMPAIGN_ID)
    parser.add_argument("--adventure-id", default=DEFAULT_ADVENTURE_ID)
    parser.add_argument("--dm-email", required=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--skip-figures",
        action="store_true",
        help="Skip minifig generation (each is an AI image call).",
    )
    args = parser.parse_args()

    headers = {AUTH_HEADER: args.dm_email}
    dry = args.dry_run

    # ── 1. Boards ─────────────────────────────────────────────────────────
    existing = httpx.get(
        f"{args.api_base}/campaigns/{args.campaign_id}/battle-maps",
        headers=headers,
        timeout=120.0,
    )
    existing.raise_for_status()
    have = {m["name"] for m in existing.json()}

    for slug, (name, _scene) in BOARDS.items():
        if name in have:
            print(f"  · '{name}' already in the library — skipped")
            continue
        png = _ROOT / "data" / "generated-maps" / f"s6-{slug}.png"
        if not png.exists():
            print(f"  ⚠ {png.name} missing — run gen_session6_boards.py (continuing)")
            continue
        if dry:
            print(f"  [dry-run] would upload {png.name} as '{name}'")
            continue
        data = png.read_bytes()
        print(f"Uploading {png.name} ({len(data) // 1024} KB) …")
        resp = httpx.post(
            f"{args.api_base}/uploads/map",
            headers=headers,
            files={"file": (png.name, data, "image/png")},
            timeout=180.0,
        )
        resp.raise_for_status()
        resp = httpx.post(
            f"{args.api_base}/campaigns/{args.campaign_id}/battle-maps",
            headers=headers,
            json={
                "name": name,
                "image_url": resp.json()["url"],
                "width": WIDTH,
                "height": HEIGHT,
                "grid_size": GRID,
            },
            timeout=60.0,
        )
        resp.raise_for_status()
        print(f"  ✓ '{name}' created")

    # ── 2. Session row ────────────────────────────────────────────────────
    sessions = httpx.get(
        f"{args.api_base}/adventures/{args.adventure_id}/sessions",
        headers=headers,
        timeout=60.0,
    )
    sessions.raise_for_status()
    session = next((s for s in sessions.json() if s.get("session_number") == SESSION_NUMBER), None)
    if session:
        print(f"  · Session {SESSION_NUMBER} exists — '{session.get('title')}'")
    elif dry:
        print(f"  [dry-run] would create Session {SESSION_NUMBER} '{SESSION_TITLE}'")
        return 0
    else:
        resp = httpx.post(
            f"{args.api_base}/adventures/{args.adventure_id}/sessions",
            headers=headers,
            json={"session_number": SESSION_NUMBER, "title": SESSION_TITLE},
            timeout=60.0,
        )
        resp.raise_for_status()
        session = resp.json()
        print(f"  ✓ Session {SESSION_NUMBER} '{SESSION_TITLE}' created")

    sid = session["id"]

    # ── 3. Token tray ─────────────────────────────────────────────────────
    table = httpx.get(f"{args.api_base}/sessions/{sid}/table", headers=headers, timeout=60.0)
    table.raise_for_status()
    tokens = list(table.json().get("tokens") or [])
    have_ids = {t.get("id") for t in tokens}

    todo = [f for f in FIGURES if f["id"] not in have_ids]
    if not todo:
        print("  · token tray already parked — skipped")
        return 0
    if args.skip_figures:
        print(f"  · --skip-figures: {len(todo)} figures NOT generated")
        return 0
    if dry:
        print(f"  [dry-run] would generate {len(todo)} figures and park the tray")
        return 0

    # Park along the top edge, one square apart, half a square down.
    x0, y0, step = GRID, GRID // 2, GRID + 8
    generated_urls: dict[str, str] = {}
    for i, fig in enumerate(todo):
        # Identical descriptions (staff, crabs, sea horses) reuse one render.
        url = generated_urls.get(fig["name"])
        if url is None:
            print(f"Generating figure: {fig['name']} …")
            resp = httpx.post(
                f"{args.api_base}/sessions/{sid}/table/figure",
                headers=headers,
                json={"name": fig["name"]},
                timeout=300.0,
            )
            if resp.status_code >= 400:
                print(f"  ⚠ figure failed ({resp.status_code}): {resp.text[:200]} — continuing")
                continue
            url = resp.json()["url"]
            generated_urls[fig["name"]] = url
        tokens.append(
            {
                "id": fig["id"],
                "kind": "custom",
                "label": "",  # shared screen: no text, ever
                "image_url": url,
                "x": x0 + i * step,
                "y": y0,
                "size": fig["size"],
                "style": "figure",
            }
        )
        print(f"  ✓ {fig['id']} parked")

    resp = httpx.patch(
        f"{args.api_base}/sessions/{sid}/table",
        headers=headers,
        json={"tokens": tokens},
        timeout=60.0,
    )
    resp.raise_for_status()
    print(f"\nDone — {len(tokens)} tokens on the Session {SESSION_NUMBER} table.")
    print("Import campaigns/session-06-scenes.json on the board for the scene presets.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
