"""Tests for portrait_service (Plan 00034).

The OpenAI image API and Vercel Blob upload are both mocked. We're
verifying:
- Prompt is built from the entity's identity fields
- The generated bytes are uploaded to the correct blob path
- The resulting URL is persisted on the entity
- Authz (DM must own the campaign) and missing keys are handled
"""

import uuid

import pytest
from sqlmodel import Session

import services.campaign_service as camp_svc
import services.character_service as char_svc
import services.npc_service as npc_svc
import services.portrait_service as portrait_svc
from domain.enums import CharacterClass
from domain.npc import NpcCreate


def _dm() -> str:
    return f"dm_{uuid.uuid4().hex[:8]}@example.com"


def _campaign(db, dm):
    return camp_svc.create_campaign(
        db, name="C", setting="Forgotten Realms", tone="Heroic", dm_email=dm
    )


def _pc(db, cid, dm):
    return char_svc.create_character(
        db,
        campaign_id=cid,
        dm_email=dm,
        player_name="P",
        character_name="Branwen",
        race="Half-Elf",
        character_class=CharacterClass.WIZARD,
        level=5,
        score_str=10,
        score_dex=14,
        score_con=12,
        score_int=18,
        score_wis=12,
        score_cha=10,
        hp_max=28,
        hp_current=28,
        ac=13,
        speed=30,
    )


def _patch_image_and_blob(
    monkeypatch, *, png_bytes: bytes = b"\x89PNGFAKE", url: str | None = None
):
    """Stub openai_client.generate_image + blob_storage.upload.

    Returns a dict capturing the args each helper was called with so
    tests can assert on prompt + blob path.
    """
    captured: dict = {}

    def fake_generate_image(prompt: str, **kwargs):
        captured["prompt"] = prompt
        captured.setdefault("image_kwargs", kwargs)
        return png_bytes

    def fake_upload(*, path: str, data: bytes, content_type: str = "image/png"):
        captured["upload_path"] = path
        captured["upload_bytes"] = data
        captured["upload_content_type"] = content_type
        return url or f"https://fake.blob/{path}"

    from integrations import blob_storage as _blob
    from services import portrait_service as _portrait

    monkeypatch.setattr(_portrait, "generate_image", fake_generate_image)
    monkeypatch.setattr(_blob, "upload", fake_upload)
    return captured


class TestGeneratePcPortrait:
    """generate_pc_portrait orchestrates prompt + gen + upload + save."""

    def test_happy_path(self, duckdb_session: Session, monkeypatch):
        """End-to-end: builds prompt, uploads, persists URL."""
        dm = _dm()
        c = _campaign(duckdb_session, dm)
        pc = _pc(duckdb_session, c.id, dm)
        captured = _patch_image_and_blob(monkeypatch)

        result = portrait_svc.generate_pc_portrait(duckdb_session, pc.id, dm)

        assert result.portrait_url == f"https://fake.blob/portraits/pc-{pc.id}.png"
        # Prompt incorporates the PC's identity
        assert "Branwen" in captured["prompt"]
        assert "Half-Elf" in captured["prompt"]
        assert "Wizard" in captured["prompt"]
        # Upload landed at the deterministic path
        assert captured["upload_path"] == f"portraits/pc-{pc.id}.png"
        assert captured["upload_bytes"] == b"\x89PNGFAKE"

    def test_style_hints_appended(self, duckdb_session: Session, monkeypatch):
        """Optional style_hints flow into the prompt."""
        dm = _dm()
        c = _campaign(duckdb_session, dm)
        pc = _pc(duckdb_session, c.id, dm)
        captured = _patch_image_and_blob(monkeypatch)

        portrait_svc.generate_pc_portrait(
            duckdb_session, pc.id, dm, style_hints="anime, watercolor"
        )
        assert "anime" in captured["prompt"].lower()

    def test_missing_pc_raises(self, duckdb_session: Session, monkeypatch):
        """Unknown PC ID raises ValueError → 404 at API."""
        _patch_image_and_blob(monkeypatch)
        with pytest.raises(ValueError):
            portrait_svc.generate_pc_portrait(duckdb_session, uuid.uuid4(), "x@y.com")

    def test_non_owner_denied(self, duckdb_session: Session, monkeypatch):
        """A different DM cannot generate a portrait for someone else's PC."""
        dm1, dm2 = _dm(), _dm()
        c = _campaign(duckdb_session, dm1)
        pc = _pc(duckdb_session, c.id, dm1)
        _patch_image_and_blob(monkeypatch)
        with pytest.raises(PermissionError):
            portrait_svc.generate_pc_portrait(duckdb_session, pc.id, dm2)


class TestGenerateNpcPortrait:
    """generate_npc_portrait orchestrates prompt + gen + upload + save."""

    def test_happy_path(self, duckdb_session: Session, monkeypatch):
        """Builds NPC-flavored prompt, uploads, persists URL."""
        dm = _dm()
        c = _campaign(duckdb_session, dm)
        npc = npc_svc.create_npc(
            duckdb_session,
            c.id,
            dm,
            NpcCreate(
                name="Captain Aldric",
                role="captain of the city watch",
                race="Human",
                gender="Male",
                age="50s",
                appearance="Steel-grey hair, scar over left eye.",
            ),
        )
        captured = _patch_image_and_blob(monkeypatch)

        result = portrait_svc.generate_npc_portrait(duckdb_session, npc.id, dm)

        assert result.portrait_url == f"https://fake.blob/portraits/npc-{npc.id}.png"
        assert "Captain Aldric" in captured["prompt"]
        # Race / role / appearance details all fold into the prompt
        assert "Human" in captured["prompt"]
        assert "captain of the city watch" in captured["prompt"]
        assert "Steel-grey hair" in captured["prompt"]
        assert captured["upload_path"] == f"portraits/npc-{npc.id}.png"

    def test_minimal_npc_still_generates(self, duckdb_session: Session, monkeypatch):
        """NPC with only a name still produces a usable prompt."""
        dm = _dm()
        c = _campaign(duckdb_session, dm)
        npc = npc_svc.create_npc(duckdb_session, c.id, dm, NpcCreate(name="Sketch"))
        captured = _patch_image_and_blob(monkeypatch)

        portrait_svc.generate_npc_portrait(duckdb_session, npc.id, dm)
        assert "Sketch" in captured["prompt"]

    def test_non_owner_denied(self, duckdb_session: Session, monkeypatch):
        """Authz: another DM cannot generate."""
        dm1, dm2 = _dm(), _dm()
        c = _campaign(duckdb_session, dm1)
        npc = npc_svc.create_npc(duckdb_session, c.id, dm1, NpcCreate(name="Sketch"))
        _patch_image_and_blob(monkeypatch)
        with pytest.raises(PermissionError):
            portrait_svc.generate_npc_portrait(duckdb_session, npc.id, dm2)

    def test_missing_npc_raises(self, duckdb_session: Session, monkeypatch):
        """Unknown NPC raises ValueError."""
        _patch_image_and_blob(monkeypatch)
        with pytest.raises(ValueError):
            portrait_svc.generate_npc_portrait(duckdb_session, uuid.uuid4(), "x@y.com")


class TestGenerateMonsterPortrait:
    """generate_monster_portrait orchestrates prompt + gen + upload + save."""

    def _make_monster(self, db):
        from db.repos.monster_repo import MonsterRepo
        from domain.monster import MonsterStatBlockCreate

        payload = MonsterStatBlockCreate(
            name="Cave Bear",
            size="Large",
            creature_type="Beast",
            ac=12,
            hp_average=42,
            hp_formula="5d10+15",
            score_str=20,
            score_dex=10,
            score_con=16,
            score_int=2,
            score_wis=13,
            score_cha=7,
            challenge_rating="2",
            xp=450,
            proficiency_bonus=2,
            speed={"walk": 40, "climb": 30},
        )
        return MonsterRepo.create(db, payload)

    def test_happy_path(self, duckdb_session: Session, monkeypatch):
        """Builds prompt, uploads, persists URL on the monster row."""
        monster = self._make_monster(duckdb_session)
        captured = _patch_image_and_blob(monkeypatch)

        result = portrait_svc.generate_monster_portrait(duckdb_session, monster.id, "dm@x.com")
        assert result.image_url == f"https://fake.blob/portraits/monster-{monster.id}.png"
        assert "Cave Bear" in captured["prompt"]
        assert captured["upload_path"] == f"portraits/monster-{monster.id}.png"

    def test_missing_monster_raises(self, duckdb_session: Session, monkeypatch):
        """Unknown monster ID raises ValueError."""
        _patch_image_and_blob(monkeypatch)
        with pytest.raises(ValueError):
            portrait_svc.generate_monster_portrait(duckdb_session, uuid.uuid4(), "dm@x.com")

    def test_monster_prompt_folds_identity(self, duckdb_session: Session):
        """Monster prompt mentions name + size + creature type."""
        monster = self._make_monster(duckdb_session)
        prompt = portrait_svc._build_monster_prompt(monster, None)
        assert "Cave Bear" in prompt
        assert "Large" in prompt
        assert "Beast" in prompt
        assert "bestiary" in prompt.lower()


class TestOpenAiErrorWrapping:
    """OpenAI SDK errors must come out as RuntimeError so the router
    can return a 502 with proper CORS headers (Plan 34 bugfix)."""

    def test_openai_error_becomes_runtime_error(self, monkeypatch):
        """Any openai.OpenAIError surfaces as RuntimeError from generate_image.

        Real-world trigger that broke production: a 400 with
        ``billing_hard_limit_reached``. The constructor for
        openai.BadRequestError has a finicky signature, so we use the
        base class directly — the catch in openai_client is on
        ``openai.OpenAIError``, which covers every concrete subclass.
        """
        import openai

        from integrations import openai_client

        class _FakeImages:
            def generate(self, **kwargs):
                raise openai.OpenAIError("Billing hard limit has been reached.")

        class _FakeClient:
            images = _FakeImages()

        monkeypatch.setattr(openai_client, "_get_client", lambda: _FakeClient())

        with pytest.raises(RuntimeError) as excinfo:
            openai_client.generate_image("a wizard")
        assert "OpenAI image API error" in str(excinfo.value)
        assert "Billing hard limit" in str(excinfo.value)


class TestPromptBuilder:
    """Direct exercise of the internal prompt builders for fast feedback."""

    def test_pc_prompt_includes_default_style(self, duckdb_session: Session):
        """The default painterly-fantasy style hint is always in the prompt."""
        dm = _dm()
        c = _campaign(duckdb_session, dm)
        pc = _pc(duckdb_session, c.id, dm)
        prompt = portrait_svc._build_pc_prompt(pc, None)
        assert "Painterly fantasy" in prompt

    def test_npc_prompt_handles_missing_fields(self, duckdb_session: Session):
        """Bare NPC still produces a valid prompt without 'None' artifacts."""
        from domain.npc import Npc

        npc = Npc(name="Mystery", campaign_id=uuid.uuid4())
        prompt = portrait_svc._build_npc_prompt(npc, None)
        assert "Mystery" in prompt
        assert "None" not in prompt
